# Generated by Django 3.2.13 on 2023-06-11 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='street',
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='dob',
            field=models.CharField(max_length=10, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='gender',
            field=models.CharField(max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='propic',
            field=models.ImageField(blank=True, default='/default/user-profile.jpg', null=True, upload_to='userpropic/'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(max_length=30, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(max_length=30, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='house_no',
            field=models.CharField(max_length=10, null=True, verbose_name='House No'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='landmark',
            field=models.CharField(max_length=100, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pincode',
            field=models.CharField(max_length=10, null=True, verbose_name='Pincode'),
        ),
    ]
